---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lena-web
spec:
  selector:
    matchLabels:
      type: lena-web
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: lena-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - lnpwsap2
      containers:
      - name: lena-web
        image: docker.io/lenacloud/lena-web:1.3.1.2-centos7-jdk8-openjdk
#       image: docker.io/lenasupport/lena-web-custom:latest
        imagePullPolicy: Always
#
#        image: lena-web-build-test-003
#        imagePullPolicy: IfNotPresent
#        imagePullPolicy: Never
#        image: 10.81.208.224:5000/lena-web-build-test-003
#        imagePullPolicy: Always
        
        resources:
          requests:
            cpu: 200m
            # memory: 10Mi

        ports:
        - containerPort: 7180
        readinessProbe:
          httpGet:
            path: /
            port: 7180
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 7180
          initialDelaySeconds: 10
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: configmap-lena-web
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-lena-web
data:
  #LENA_MANAGER_ADDRESS: "lena-manager.default.svc.cluster.local:7700"
  LENA_MANAGER_ADDRESS: "10.81.208.155:7700"
  LENA_AGENT_RUN: "Y"
  LENA_CONFIG_TEMPLATE_ID: "lena-web"
  LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
  LENA_MANAGER_KEY: "q8Dp6NoT9tDLdit0gxu4vaMnzcYa2dwb6z7jariJSL5XR6UhCA1NKAIPZGTp8oN7Fo8t6F418J5P6oPyaIJgOw%3D%3D"
#  LENA_MANAGER_2ND_ADDRESS: "10.81.208.156:7700"
#  LENA_MANAGER_2ND_UDP: "16100"
#  LENA_MANAGER_2ND_KEY: "Mi9r4xTfd4TPSuAyGLfGAb7UwrAPiQjf4JJZkTnLcDFeA9xd%2BtSON%2B7D27uiBpnL%2F6VTaV9JMSk40lG5q6EYig%3D%3D"

  LENA_LICENSE_DOWNLOAD_URL: "manager"
  LENA_CONTRACT_CODE: "NIt0mNhMj/hWvfmlgpsZ5Q=="

---
apiVersion: v1
kind: Service
metadata:
  name: lena-web
spec:
  selector:
    type: lena-web
  ports:
  - nodePort: 31180
    port: 8280
    targetPort: 7180
  type: NodePort
  externalIPs:
  - 10.81.208.156

