---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-db-pv-claim
spec:
  storageClassName: db-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
