---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lena-session
spec:
  selector:
    matchLabels:
      name: lena-session
  serviceName: lena-session
  replicas: 2
  template:
    metadata:
      labels:
        name: lena-session
    spec:
      containers:
      - name: lena-session
#        image: docker.io/lenasupport/lena-session:1.3.1c.1-centos7-jdk8-openjdk
        image: docker.io/lenacloud/lena-session:1.3.1.2-centos7-jdk8-openjdk
        imagePullPolicy: Always
        ports:
        - containerPort: 5180
        envFrom:
        - configMapRef:
            name: configmap-lena-session
        tty: true
        readinessProbe:
          exec:
            command:
            - /usr/local/lena/servers/sessionServer/health.sh
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - /usr/local/lena/servers/sessionServer/health.sh
          initialDelaySeconds: 30
          periodSeconds: 5
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-lena-session
data:
  LENA_SESSION_0_ADDRESS: "lena-session-0.lena-session.default.svc.cluster.local:5180"
  LENA_SESSION_1_ADDRESS: "lena-session-1.lena-session.default.svc.cluster.local:5180"
  LENA_MANAGER_ADDRESS: "10.81.208.155:7700"
#  LENA_MANAGER_ADDRESS: "lena-manager.default.svc.cluster.local:7700"
  LENA_SESSION_EXPIRE_SEC: "1800"
  LENA_CONFIG_TEMPLATE_ID: "lena-session"
  LENA_CONFIG_SHARE_SESSION: "N"
---   
apiVersion: v1
kind: Service
metadata:
  name: lena-session
spec:
  selector:
    name: lena-session
  clusterIP: None
  
